import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    tools: 'src/tools/index.ts',
    context: 'src/context/index.ts',
    permissions: 'src/permissions/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  external: ['uuid'],
  banner: {
    js: '// Generated by Supanova SDK',
  },
});
